SELECT C."COUNTRY_NAME" AS country, COUNT(*) AS count
FROM "EMPLOYEES" E
         join public."DEPARTMENTS" D on D."DEPARTMENT_ID" = E."DEPARTMENT_ID"
         join public."LOCATIONS" L on L."LOCATION_ID" = D."LOCATION_ID"
         join public."COUNTRIES" C on C."COUNTRY_ID" = L."COUNTRY_ID"
WHERE LOWER(C."COUNTRY_NAME") = LOWER('United Kingdom')
  AND E."EMPLOYEE_ID" IN (SELECT DISTINCT E."MANAGER_ID" FROM "EMPLOYEES" E WHERE E."MANAGER_ID" IS NOT NULL)
group by C."COUNTRY_NAME";
