version: "3.9"
services:
  postgres:
    container_name: coin_db
    image: postgres:latest
    volumes:
      - ../volumes:/volumes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coin_db
    ports:
      - "5432:5432"
