CREATE TABLE CURRENCY
(
    CURRENCY_ID   SERIAL PRIMARY KEY,
    CURRENCY_NAME CHAR(3) NOT NULL UNIQUE
);

CREATE INDEX CURRENCY_NAME_INDEX ON CURRENCY (CURRENCY_NAME);

CREATE TABLE CASH_FLOW
(
    CASH_FLOW_ID    BIGSERIAL PRIMARY KEY,
    REPORT_DATE     DATE           NOT NULL,
    CLIENT_NAME     VARCHAR(50)    NOT NULL,
    CURRENCY_ID     BIGSERIAL,
    AMOUNT_CURRENCY NUMERIC(20, 4) NOT NULL,
    FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID)
);

CREATE INDEX CASH_FLOW_DATE_INDEX ON CASH_FLOW (REPORT_DATE);

CREATE TABLE CURRENCY_RATES
(
    CURRENCY_RATES_ID BIGSERIAL PRIMARY KEY,
    REPORT_DATE       DATE           NOT NULL,
    CURRENCY_ID       BIGSERIAL,
    CURRENCY_RATE     NUMERIC(20, 4) NOT NULL CHECK (CURRENCY_RATE >= 0),
    FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID),
    UNIQUE (REPORT_DATE, CURRENCY_ID)
);

CREATE INDEX CURRENCY_RATES_DATE_INDEX ON CURRENCY_RATES (REPORT_DATE);
