CREATE TABLE CASH_FLOW (
    REPORT_DATE DATE NOT NULL,
    CLIENT_NAME VARCHAR(50) NOT NULL,
    CURRENCY CHAR(3) NOT NULL,
    AMOUNT_CURRENCY NUMERIC(20, 4) NOT NULL
);

CREATE TABLE CURRENCY_RATES (
    REPORT_DATE DATE NOT NULL,
    CURRENCY CHAR(3) NOT NULL,
    CURRENCY_RATE NUMERIC(20, 4) NOT NULL CHECK (CURRENCY_RATE >= 0)
);
