version: "3.9"
services:
  postgres:
    container_name: hr_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hr_db
    ports:
      - "5432:5432"
