SELECT C."COUNTRY_ID", SUM(E."SALARY") AS "salary sum" FROM "COUNTRIES" C
JOIN public."LOCATIONS" L on C."COUNTRY_ID" = L."COUNTRY_ID"
JOIN public."DEPARTMENTS" D on L."LOCATION_ID" = D."LOCATION_ID"
JOIN public."EMPLOYEES" E on D."DEPARTMENT_ID" = E."DEPARTMENT_ID"
GROUP BY C."COUNTRY_ID"
HAVING COUNT(E."EMPLOYEE_ID") != 0
ORDER BY "salary sum", "COUNTRY_ID"
