SELECT D."DEPARTMENT_NAME", J."JOB_TITLE" FROM "DEPARTMENTS" D
JOIN public."EMPLOYEES" E on D."DEPARTMENT_ID" = E."DEPARTMENT_ID"
JOIN public."JOBS" J on J."JOB_ID" = E."JOB_ID"
GROUP BY D."DEPARTMENT_NAME", J."JOB_TITLE"
HAVING COUNT(J."JOB_ID") = 1
ORDER BY D."DEPARTMENT_NAME", J."JOB_TITLE"
