SELECT D."DEPARTMENT_ID", "DEPARTMENT_NAME", COUNT(E."EMPLOYEE_ID") AS "count" FROM "DEPARTMENTS" D
JOIN public."EMPLOYEES" E on D."DEPARTMENT_ID" = E."DEPARTMENT_ID"
GROUP BY "DEPARTMENT_NAME", D."DEPARTMENT_ID"
ORDER BY COUNT(E."EMPLOYEE_ID"), D."DEPARTMENT_NAME"
